[[faq-en]]
[role="chunk-page chunk-toc"]
== Frequently Asked Questions

--
--


[[faq-en-general]]
=== General

[[faq-en-general-q1]]
==== Q: Can I transfer my current user tokens from another service to WonderPush?

**A:**
Yes you can! You just need to send us the push tokens list in the following Json format and we will import them into WonderPush.

[[faq-en-general-q2]]
==== Q: What are opt in active users?

**A:**
Opt in active users is a key indicator calculated by taking the number of unique users for a 90 day period who are still registered to your push notifications.

[[faq-en-general-q3]]
==== Q: Is WonderPush a free service?

**A:**
WonderPush is a free service with the unlimited push notifications on the Basic account. Premium account unlocks additional features like Remote API, multi-account support and more.

[[faq-en-general-q4]]
==== Q: What is your pricing model?

**A:**
You can find our regular account pricing at: https://www.wonderpush.com/pricing[https://www.wonderpush.com/pricing]

[[faq-en-general-q5]]
==== Q: Is there a limit to the number of pushes I can send?

**A:**
There are no limits on the number of push notifications.


[[faq-en-web]]
=== Website integration

[[faq-en-web-q1]]
==== Q: Do web push notifications appear on mobile screens?

**A:**
[cols=",",options="header,autowidth"]
|=========================================================
|Platform |Web push support

|Android Chrome |YES

|iOS Chrome |Not yet

|iOS Safari |Not yet
|=========================================================

[[faq-en-web-q2]]
==== Q: What’s the difference between “Web Push Notifications” and the Push Notifications I get on my mobile phone?

**A:**
Web push notifications and mobile push notifications are very similar. Web Push Notifications work just like push notifications for apps. They display your website icon and notification text, which users can click to go right to your website.

While mobile notifications are delivered by a mobile application, Web Push are addressed by websites through web browsers. Currently Apple Safari and Google Chrome Web support push notifications. Mozilla Firefox should support soon.

*How do web push notifications work on the user side?*

When a user visits your site, it must register through a small prompt window displayed by the browser. Therefore, he subscribes to the push notifications that you can easily send from the WonderPush dashboard. These are instantly displayed on the screen of the user even if it 's not on your website.

[[faq-en-web-q3]]
==== Q: Will Wonderpush affect my website’s performance?

**A:**
WonderPush should have no negative impact on your website’s performance. WonderPush script makes the loading of the SDK asynchronous. Thus, it won’t slow down the loading of your pages. The snippet loads a very short script that detects the minimum features required for push notification support. If browser support is present, it then injects the whole SDK. Our SDK is hosted on a worldwide CDN. It automatically loads the latest version available without risking incompatible code changes.

[[faq-en-web-q4]]
==== Q: Does WonderPush work on HTTP-only websites?

**A:**
Sure! WonderPush works on websites that are not using HTTPS protocol, without any additional work on your part.

[[faq-en-web-q5]]
==== Q: My site uses multiple subdomains like foobar.domain.com. Will WonderPush work on it?

**A:**
Yes. WonderPush supports multiple subdomains websites, without extra work.

[[faq-en-web-q6]]
==== Q: How do I implement a push notification subscription switch like on wonderpush.com?

**A:**
You just have to find an appropriate place in your page and copy/paste the following code:

[source,HTML]
---------------------------------------------------------------------
<div id="wonderpush-subscription-switch" data-sentence="Receive our latest news by web push: " data-on="YES" data-off="NO"></div>
---------------------------------------------------------------------
Note: You must have installed the main WonderPush JavaScript snippet.

Warning: Take care to not change the div id, otherwise the switch will no longer work.

Note: Don't forget to also display the switch on your mobile site.

[[faq-en-web-q7]]
==== Q: How to install WonderPush via Google Tag Manager?

**A:**
You already use Google Tag Manager on your website and you would like to use it to integrate the WonderPush javascript snippet into your pages.

Here are the steps to follow:

. Sign in to https://tagmanager.google.com[Google Tag Manager]
. Select ‘Add a new tag’ and then choose Custom HTML Tag
. Name your tag "WonderPush GTM"
. Copy from https://dashboard.wonderpush.com[WonderPush] (section +Settings / Keys+), the javascript snippet and paste it into the textbox
. Decide to fire on All Pages
. Click "Create Tag"
. Publish

That's done, you can start sending Web push to your users. 


[[faq-en-web-q8]]
==== Q: I don't see the switch on my page [TROUBLESHOUTING]

**A:**

* Make sure the switch div is present into the source of your page
* Make sure that the its id of "wonderpush-subscription-switch"


[[faq-en-ios]]
=== iOS

[[faq-en-ios-q1]]
==== Q: How can I test my application before submitting it to the iTunes App Store?

**A:**
You can use TestFlight for testing your iOS application before submitting to Apple validation process. Applications tested through TestFlight will use the production APNS certificate.
If you are still in active development, you can consider creating another application in the WonderPush dashboard, and change the credentials (clientId and clientSecret) given in the SDK initialization step accordingly.

[[faq-en-ios-q2]]
==== Q: How do I setup both the development (Sandbox) and production notifications for iOS?

**A:**
Since you can only put one APNs push notification certificate at a time in your iOS apps, you should create two iOS projects in XCode, a test project and a publishable project. Then create two applications in the WonderPush dashboard, one for each project. They won’t share the same credentials nor certificates.
You can also use only one iOS project, provided that you change the credentials (clientId and clientSecret) given in the SDK initialization step accordingly.



[[faq-fr-ios-q3]]
==== Q: How to renew expiring iOS push notification certificates?

**A:**
For your applications to be able to receive push notifications, the certificate (.p12 file) indicated on https://dashboard.wonderpush.com[WonderPush] (section +Settings / Keys+) must be up to date (fichier p12). If this is not the case , you must generate a new certificate and replace the old one on WonderPush. Nothing will need to be updated in your app and you won’t have to submit a new version of the app.

Here are the steps to follow:

. In https://developer.apple.com/account/ios/certificate/certificateList.action[Apple Developer Certificates], choose the section +Certificates, Identifiers & Profiles+ and click +Add a new certificate+ (Add a new certificate)
. Select +Apple Push Notification SSL (Production)+ and clcik +Continue+
. Select the same App ID you are using for the current certificate and click +Continue+
. You need then to generate a CSR (Certificate Signing Request) from your Mac:
.. Go into +Finder / Applications / Utilities+ and launch +Keychain Access+
.. Into Keychain Access menu, select +Keychain Access > Certificate Assistant > Request a Certificate from a Certificate Authority...+
.. Enter your +Email Address+
.. Enter a name like: +YourApp Production APNs+ (leave +CA Email+ blank)
.. Select +Saved to disk+ and click +Continue+
. You then need to upload the file you just created
. Click +Generate+, then +Download+ and open the certificate with +Keychain Access+
. Click +File / Export Items...+ (you can leave the password blank)
. Go then to https://dashboard.wonderpush.com[WonderPush] in the +Settings / Keys+ section and upload the +.p12+ file
