[[faq-fr]]
[role="chunk-page chunk-toc"]
== Foire aux questions

--
--


[[faq-fr-general]]
=== Général

[[faq-fr-general-import-users]]
==== Q : Puis-je transférer mes push tokens actuels d'un autre service vers WonderPush ?

**R :**
Oui, c'est possible ! Vous devez simplement nous fournir une liste de vos push tokens au format Json et nous l'importerons dans votre nouveau compte WonderPush.

[[faq-fr-general-optin-active-users]]
==== Q : Que signifie Utilisateurs opt-in actifs ?

**R :**
Les utilisateurs opt-in actifs, est la partie de vos utilisateurs uniques actifs des 90 derniers jours qui acceptent toujours de recevoir vos notifications.

[[faq-fr-general-free-service]]
==== Q : WonderPush est-il un service gratuit ?

**R :**
Oui, WonderPush permet d'envoyer gratuitement un nombre illimité de push notifications sans même avoir à entrer votre numéro de carte bancaire. Un compte Premium permet de bénéficier de fonctionnalités supplémentaires comme l'accès à l'API WonderPush ou le support de comptes multi-utilisateurs.

[[faq-fr-general-pricing]]
==== Q : Quel est votre modèle de facturation ?

**R :**
Vous pouvez retrouver nos taris sur la page : https://www.wonderpush.com/fr/pricing[https://www.wonderpush.com/fr/pricing]

[[faq-fr-general-unlimited-notifications]]
==== Q : Y a-t-il une limite au nombre de notification que je peux envoyer ?

**R :**
Non, il n'y a aucune limite. Vous pouvez envoyer autant de notifications que vous souhaitez.

[[faq-fr-general-staff-limited-views]]
==== Q: Comme puis-je restreindre une personne de mon équipe à envoyer des notifications aux utilisateurs d'un pays uniquement (ou parlant une langue, ou abonnés à une catégorie en particulier) ?

**A:**
Cette fonctionnalité n'est disponible qu'avec un compte Premium. Prenons un exemple concret. Par exemple, votre application a une audience mondiale et vous disposez d'éditeur pour chaque langue. Vous souhaitez que votre éditeur Anglais (nommons-le John) ne puisse créer des segments et envoyer des notifications à une audience anglophone uniquement.

Voici comment il faut procéder :

. Sélectionnez l'onglet `Réglages/Vues` et clqiez sur `Créer une vue`
. Choisissez les règles permettant de limiter le champ d'audience dans lequel John a le droit d'agir : `Langue` est parmi  `English`. Nommez cette vue "Audience Anglophone"
. Cliquez sur `Sauvegarder`
. Puis, sélectionnez `Réglages/Staff`
. Associez la vue "Audience Anglophone" au profil de John 

Quand vous naviguez sur votre tableau de bord WonderPush, vous devriez maintenant voir dans le chemin de navigation, un nouveau menu proposant les choix "Vue complète" et "Vue audience anglophone" alors que John verra uniquement la "Vue audience anglophone". Vous seul pouvez créer des segments au niveau "Vue complète". Les segments et notifications créés au sein d'une vue spécifique ne sont visibles qu'en son sein. Les segments créés au niveau "Vue complète" sont visibles dans toutes les vues et ainsi réutilisables dans chacune des vues en prenant en compte les règles spécifiques à celle-ci.


[[faq-fr-web]]
=== Sites Web

[[faq-fr-web-mobile-support]]
==== Q : Les push web s'affichent elle aussi sur les téléphones mobiles ?

**R :**
[cols=",",options="header,autowidth"]
|=========================================================
|Plateforme |Support des push web

|Android Chrome |OUI

|Android Firefox |OUI

|Android Opera |OUI

|iOS Safari |Pas encore

|iOS Chrome |Pas encore

|iOS Firefox |Pas encore
|=========================================================

[[faq-fr-web-web-vs-native]]
==== Q : Quelle est la différence entre les notifications web et les notifications que je reçois sur mon mobile ?

**R :**
Les notifications web et les notifications push mobiles sont très similaires . Elles contiennent quelques lignes de texte et une URL qui pointent vers un contenu .

Alors que les notifications mobiles sont fournies par une application mobile, les Push Web sont adressées par les sites Web via les navigateurs Web. Actuellement Apple Safari, Google Chrome et Mozilla Firefox supportent les notifications Push. Internet Explorer devrait les soutenir bientôt.

*Comment les notifications web fonctionnent-elles du point de vue de l'utilisateur ?*

Quand un utilisateur visite votre site , il doit s'enregistrer via une petite fenêtre affichée par le navigateur. Dès lors, il est abonné aux notifications push que vous pouvez facilement envoyer depuis le tableau de bord de WonderPush. Celles-ci s'afficheront instantanément à l'écran de l'utilisateur même si celui-ci n'est pas sur votre site.

[[faq-fr-web-performance-impact]]
==== Q : WonderPush dégradera-t-il les performances de mon site ?

**R :**
WonderPush n'aura aucun impact négatif sur les performances de votre site web. Le script WonderPush à coller sur votre site rend le chargement du SDK asynchrone. Ainsi, il ne fera pas ralentir le chargement de vos pages. Le bout de code charge un script très court qui détecte les caractéristiques minimales requises pour le soutien de notification push. Si le support du navigateur est présent, il injecte alors l'ensemble du SDK. Notre SDK est hébergé sur un CDN dans le monde entier. Il charge automatiquement la dernière version disponible sans risquer des changements de code incompatibles .

[[faq-fr-web-http-support]]
==== Q : WonderPush fonctionne-t-il sur un site uniquement en HTTP ?

**R :**
Tout à fait. WonderPush fonctionne sur tous les sites, même ceux qui n'utilisent pas le protocole HTTPS et ce, sans travail supplémentaire de votre part.

[[faq-fr-web-subdomains-support]]
==== Q : Mon site utilise plusieurs sous-domaines. WonderPush fonctionnera-t-il avec?

**R :**
Oui. WonderPush fonctionne également sur les sites ayant plusieurs sous-domaines du type foobar.votresite.com, et ce sans intégration supplémentaire de votre part.

[[faq-fr-web-subscription-switch]]
==== Q : Comment intégrer un bouton oui/non comme sur le site Wonderpush.com ?

**R :**
Pour cela, il vous suffit de trouver la place la plus appropriée dans votre page et de copier coller le code suivant :

[source,HTML]
----
<div id="wonderpush-subscription-switch" data-sentence="Recevoir nos dernières infos : " data-on="OUI" data-off="NON"></div>
----

Note : Pour que le bouton fonctionne, vous devez aussi avoir installé le code JavaScript principal.

Attention : Ne changez pas l'id du div, sans quoi le bouton ne fonctionnera plus.

Note : N'oubliez pas d'afficher le bouton sur votre site mobile également.

[[faq-fr-web-google-tag-manager-support]]
==== Q: Comment installer WonderPush en utilisant Google Tag Manager ?

**R:**
Vous utilisez déjà Google Tag Manager sur votre site et vous souhaiteriez utiliser ce moyen pour insérer le javascript WonderPush dans vos pages.

Voilà les étapes à suivre :

. Connectez-vous sur https://tagmanager.google.com[Google Tag Manager]
. Sélectionnez `Ajouter une balise`, puis nommez votre balise "WonderPush GTM" 
. Choisissez `Balise HTML personnalisée`
. Copiez depuis https://dashboard.wonderpush.com[WonderPush] (onglet +Réglages / Clés+), le bout de code javascript et copiez-le dans la boîte de texte sur Google Tag Manager
. Choisissez un `déclenchement` sur `toutes les pages`
. Cliquez `Créer une balise`
. Cliquez sur `Publier`

C'est terminé, vous pouvez commencer à envoyer des push web à vos utilisateurs. 

[[faq-fr-web-cannot-see-switch]]
==== Q : Je ne vois pas le bouton Oui / Non sur mon site [DEPANNAGE]

**R :**

* Assurez-vous que le div nécessaire à l'affichage du bouton soit bien présent dans le code HTML de vos pages
* Assurez-vous que l'id de ce div est bien "wonderpush-subscription-switch"


[[faq-fr-ios]]
=== iOS

[[faq-fr-ios-testing]]
==== Q : Comment puis-je tester mon application avant de la soumettre dans l'App Store iTunes ?

**R :**
Vous pouvez utiliser TestFlight pour tester votre application iOS avant de la soumettre à Apple. Les applications testées via TestFlight peuvent utiliser le certificat de production de APNS.
Si vous êtes encore en développement actif, vous pouvez envisager de créer une autre application dans le tableau de bord WonderPush, et de modifier les informations d'identification (clientId et clientSecret) données dans l'étape d'initialisation du SDK.

[[faq-fr-ios-multiple-environments-support]]
==== Q : Comment configurer à la fois un environnement de production et un de developpement (Sandbox) pour les notifications sur iOS ?

**R :**
Etant donné que vous ne pouvez mettre qu'un seul certificat de push notification APN à la fois dans vos applications iOS, vous devez créer deux projets iOS dans Xcode, un projet de test et un projet pour la production. Ensuite, créez deux applications dans le tableau de bord WonderPush, un pour chaque projet. Ils ne partageront pas les mêmes informations d'identification ni les mêmes certificats .
Vous pouvez également utiliser un seul projet iOS, à condition que vous modifiez les informations d'identification (clientId et clientSecret) données dans l'initialisation étape de SDK.

[[faq-fr-ios-renew-certificate]]
==== Q : Comment renouveler un certificat APNs (Apple Push Notification service) expiré ?

**R :**
Pour que vos applications soient en mesure de recevoir des push notifications, il est indispensable que le certificat (fichier p12) renseigné sur https://dashboard.wonderpush.com[WonderPush] (onglet +Réglages / Clés+) soit à jour. Si ce n'est pas le cas, vous devez générer un nouveau certificat et remplacer l'ancien sur WonderPush. Il ne sera pas nécessaire de metre à jour votre application et vous n'aurez pas à soumettre de nouvelle version de celle-ci.

Voici les étapes à suivre :

. Dans https://developer.apple.com/account/ios/certificate/[Apple Developer Certificates], cliquez sur le bouton `+` (Add)
. Sélectionnez +Apple Push Notification service SSL (Sandbox & Production)+ et cliquez sur +Continue+
. Sélectionnez l'+App ID+ que vous utilisez pour le certificat expiré et cliquez sur +Continue+
. Vous devez maintenant générer un fichier CSR (Certificate Signing Request) depuis votre Mac :
.. Allez dans +Finder / Applications / Utilitaires+ et lancez l'application +Trousseaux d'accès+
.. Dans le menu de Trousseaux d'accès, sélectionnez +Trousseaux d'accès > Assistant de certification > Demander un certificat à une autorité de certificat...+
.. Entrez votre +Adresse email+
.. Puis un nom du type : +VotreAppli Production APNs+ (laissez +CA Email+ vide)
.. Sélectionnez +Enregistrée sur le disque+ et cliquez sur +Continuer+
. Vous devez uploader le fichier que vous avez créé
. Cliquez sur +Continue+, puis +Download+ et ouvrez enfin le certificat avec +Trousseaux d'accès+
. Retrouvez votre nouveau certificat sous le trousseau +login+ dans le coin supérieur gauche et dans la catégorie +Mes certificats+ dans le coin inférieur gauche.
. Cliquez sur +Fichier / Export des éléments...+ (vous pouvez laisser le mot de passe vide)
. Allez enfin sur https://dashboard.wonderpush.com[WonderPush] à l'onglet +Réglages / Clés+ et uploadez le fichier +.p12+
