[[faq-glossary]]
[role="chunk-page chunk-toc"]
== Glossary

Application access token::
  This secret can be used as the API password for any API call, and can do anything – guard it carefully, and never embed it in an application you distribute to users.

Application id::
  It an internal id that identifies your application or website. 

Client id::
  The application key is the unique identifier for your application, and is used to authenticate the application for API calls.

Client secret::
  A secret used to authorize requests for low-security API calls from your mobile application. This secret is intended to be embedded inside a mobile application, and as such is limited it what it can do. 
  
Custom event::
  A Custom Event is a user action, taken in-app or in-Website.  

Google Cloud Messaging (GCM)::
  https://developers.google.com/cloud-messaging/[Google Cloud Messaging (GCM), "window="_blank"] is the transport method that WonderPush employs for notification to Android devices.

Opt-in user::
  An end user of a mobile application for which notifications are currently set to on. You may alternatively think of an opt-in user as a device that is eligible for push notifications, because an individual user, i.e., person, may have multiple devices registered with the app.

Opt-out user::
  An end user of a mobile application for which notifications are currently set to off. You may alternatively think of an opt-out user as a device that is not eligible for push notifications, because an individual user, i.e., person, may have multiple devices registered with the app.

UTC::
  Coordinated Universal Time. Equivalent to GMT without daylight savings.

Web key::
  An API key dedicated to authorize requests for low-security API calls from your website. 
  
